### PR TITLE
fix(types): switch order of schema type arguments - @macinjoke

### PR DESCRIPTION
**Pull request by macinjoke**
### Description

fixed this.

スクリーンショット 2020-03-01 午前0 13 46

https://github.com/prescottprue/react-redux-firebase/pull/826/files#r386035738

### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
- [x] Docs updated with any changes or examples if applicable
- [x] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by macinjoke** [comment]
https://github.com/prescottprue/react-redux-firebase/pull/826/files#r386035738

**Comment by prescottprue** [comment]
Switching these arguments was in attempt to get the [schema feature added in this PR](https://github.com/prescottprue/react-redux-firebase/pull/826) to work as expected. Is there a reason for going back? I understand that it became breaking for this switch, but seems like the right move since it was the original intention. What are your thoughts?

**Comment by macinjoke** [comment]
Sorry, it was an inadequate change.
I should have also switched the parts that use `FirebaseReducer.Reducer`. So I changed `firebaseReducer` and` makeFirebaseReducer` as well. 5929bcb

The reason for ordering the `FirebaseReducer.Reducer` type arguments in the order of `Scheme`, `ProfileType` is simply that TypeScript throws an error, as shown in the screenshot image. TypeScript generics cannot bring ordinary arguments after arguments with default values. (Because the first default argument doesn't make sense)

**Comment by prescottprue** [comment]
It seems like the [the ProfileType is set to an object already](https://github.com/prescottprue/react-redux-firebase/blob/master/index.d.ts/#L1104), so we should be able to remove the default setting there right?

**Comment by macinjoke** [comment]
> It seems like the the ProfileType is set to an object already

It seems that the ProfileType set here has nothing to do with the ProfileType of FirebaseReducer.Reducer.
The type argument ProfileType used in generics can be either Foo or Bar.

I think the type argument ProfileType is necessary for the user to specify a type like `firebaseReducer<Foo, Bar>`. (In this case, Bar becomes the ProfileType.)

**Comment by prescottprue** [comment]
Thanks for the PR. Released in [v3.2.0](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.2.0)

**Comment by rscotten** [comment]
@prescottprue, @macinjoke 

Guys!  Stop changing the order!  This is going to break our code again!

@prescottprue I wish you would have asked me about this.

Just give both types defaults like this: 

```typescript
export function firebaseReducer<
  UserType,
  Schema extends Record<string, Record<string | number, string | number>>
>(state: any, action: any): FirebaseReducer.Reducer<UserType, Schema>

export function makeFirebaseReducer<
  UserType = {},
  Schema extends Record<string, Record<string | number, string | number>> = {}
>(): (state: any, action: any) => FirebaseReducer.Reducer<UserType, Schema>
```

```typescript
export namespace FirebaseReducer {
  export interface Reducer<
    ProfileType = {},
    Schema extends Record<string, Record<string | number, string | number>> = {}
  > {
```

This way nobody needs to add the `UserType` or `Schema` if they don't want to.

And `UserType` should always come first because it's more important than `Schema`.

Please make the changes I gave above or let me know and I'll submit a PR to make the change.

**Comment by rscotten** [comment]
@prescottprue @macinjoke  I submitted PR #888 with the preferred approach to solving this type error.

**Comment by rscotten** [comment]
@macinjoke You could have solved this problem without creating a PR with breaking changes simply by doing this:

```typescript
  FirebaseReducer.Reducer<{}, {}>
```

**Comment by prescottprue** [comment]
Thanks for the PR @rscotten! For some reason I thought that is what the last PR is doing, which is why I included it in 3.2.0.

**Comment by rscotten** [comment]
@prescottprue Thank you! :)

**Comment by macinjoke** [comment]
> This way nobody needs to add the UserType or Schema if they don't want to.

> And UserType should always come first because it's more important than Schema.

> Please make the changes I gave above or let me know and I'll submit a PR to make the change.

> @prescottprue @macinjoke I submitted PR #888 with the preferred approach to solving this type error.



> @macinjoke You could have solved this problem without creating a PR with breaking changes simply by doing this:
> 
> ```ts
>   FirebaseReducer.Reducer<{}, {}>
> ```

Sounds great! Thank you.

**Comment by JonnyBoy333** [comment]
Would someone here be kind enough to share an example of how to use the Schema part of `FirebaseReducer.Reducer(ProfileType, Schema)`? Seems like no matter what I put in there I get the error: 
`Type 'DBSchema' does not satisfy the constraint 'Record<string, Record<string | number, string | number>>'.
  Index signature is missing in type 'DBSchema'.`

Trying to do something simple like:
``` typescript
interface IContact {
  name: string;
  email: string;
}

// create schema for the DB
interface DBSchema {
  contacts: IContact
}

export interface RootState {
  firebase: FirebaseReducer.Reducer<IProfile, DBSchema>; // <--- Error here
  firestore: FirestoreReducer.Reducer;
  localSettings: ILocalSettings
  loading: ILoading
}

const appReducer = combineReducers<RootState>({
  localSettings: settingsReducer,
  loading: loadingReducer,
  firebase: firebaseReducer,
  firestore: firestoreReducer,
});
```

**Comment by rscotten** [comment]
@JonnyBoy333 The original PR was #826 which broke the codebase due to putting the new `Schema` type before the `Profile` type in `FirebaseReducer.Reducer`, which was later fixed.   So make sure you're on the latest version (3.3.0).  

The schema type only works for the RealTime DB (not Firestore). I don't use the RTDB, so I can't really help you debug this.  @vicrac or @prescottprue can you help?

**Comment by rscotten** [comment]
@JonnyBoy333 you can hack it by doing this:

```typescript
combineReducers<RootState>({
    firebase: firebaseReducer as any, // <-- add "as any"
  });
```

**Comment by rscotten** [comment]
@JonnyBoy333 

I figured it out.  We just need to change the type definitions to:

```typescript
export function firebaseReducer<
  UserType extends Record<string, any> = {},
  Schema extends Record<string, any> = {}
>(state: any, action: any): FirebaseReducer.Reducer<UserType, Schema>

export function makeFirebaseReducer<
  UserType extends Record<string, any> = {},
  Schema extends Record<string, any> = {}
>(): (state: any, action: any) => FirebaseReducer.Reducer<UserType, Schema>
```

I'll submit a PR.

**Comment by rscotten** [comment]
@JonnyBoy333 figured it out.  The type definitions need to be changed in `index.d.ts`:

```typescript
export function firebaseReducer<
  UserType extends Record<string, any> = {},
  Schema extends Record<string, any> = {}
>(state: any, action: any): FirebaseReducer.Reducer<UserType, Schema>

export function makeFirebaseReducer<
  UserType extends Record<string, any> = {},
  Schema extends Record<string, any> = {}
>(): (state: any, action: any) => FirebaseReducer.Reducer<UserType, Schema>
```

**Comment by rscotten** [comment]
@JonnyBoy333 @prescottprue submitted PR #pull to fix this.

**Comment by JonnyBoy333** [comment]
@rscotten Wow that was quick, thank you and also thanks for updating the documentation.

I tried copying your updated index.d.ts into my project and I am still getting an error (even with your documentation example). It's the same error as before and I think it's because there is another reducer type on line 1134. Here:
https://github.com/prescottprue/react-redux-firebase/blob/cfc516c428883a7845d6f9fc8ee671ce80e808f7/index.d.ts#L1134

**Comment by rscotten** [comment]
@JonnyBoy333 Good catch.  Fixed.  Thanks!

**Comment by JonnyBoy333** [comment]
@rscotten Confirmed, no more errors here.

I hope someday someone will do the same for Firestore schemas 🤞.

**Pull request merged**
