### PR TITLE
fix(firebaseConnect): move hoistStatics to allow static methods to be copied - @jeloagnasin

### LINKED ISSUE #732: bug(HOCs): Static methods are not copied over
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

Static methods are not copied over if I use `firebaseConnect`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**

See: https://github.com/jeloagnasin/rrf-testing/blob/master/App.js for minimal demo.

In the demo, without the `firebaseConnect()`, the title of the screen will show up in the navigation header. But if I wrap my component in `firebaseConnect()`, the title is not displayed. Essentially, `navigationOptions` is not called.

```javascript
const Stack = createAppContainer(createStackNavigator({
  // Testing: firebaseConnect()(Testing),
  Testing,
}));
```

**What is the expected behavior?**

Static methods are copied over like in v2.3.0.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

* react-redux-firebase@^3.0.0-alpha.13 (worked in 2.3.0)
* react-redux@^6.0.0

If you need more info, let me know. Thanks!

### PR DESCRIPTION
**Pull request by jeloagnasin**
### Description

Fixes #732 

### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
- [x] Docs updated with any changes or examples if applicable
- [x] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by jeloagnasin** [comment]
This has worked for me. But I'm not really sure if there are any other repercussions since I'm not really familiar with hooks, context, and the inner workings of `react-redux-firebase`.

**Comment by illuminist** [comment]
I'm working on overhauling `firestoreConnect` and `firebaseConnect`, will keep that in mind then.

**Comment by jeloagnasin** [comment]
@illuminist, looking forward to it! 😄Is there an ongoing branch where I can subscribe to get updates? In the meantime, I'll be using this "fix" (more like a hack) 🤣Feel free to close this PR.

**Comment by illuminist** [comment]
https://github.com/illuminist/react-redux-firebase/tree/hook-rework

I still need a bit more cleaning up. But feel free to test it and report if you find some issue.

**Comment by jeloagnasin** [comment]
Sure, I'll let you know if I find anything. I will try it on my app.

Although, I don't know where to report issues on your branch because there's no issues tab on your repo. I guess because it's forked? I think it would be best to create a PR on the main repo and tag it as WIP.

Screen Shot 2019-07-23 at 10 54 01 PM

**Comment by illuminist** [comment]
https://github.com/prescottprue/react-redux-firebase/pull/734 There you go

**Comment by prescottprue** [comment]
Awesome to hear, thanks @illuminist

**Comment by prescottprue** [comment]
As mentioned above, #734 will be a more permeant solution

**Pull request merged**
