### PR TITLE
feat(auth): add custom claims

### PR DESCRIPTION
**Pull request by joerex**
### Description

Firebase has a secure way of identifying and making claims about users with [custom claims](https://firebase.google.com/docs/auth/admin/custom-claims). This is a good way to provide roles for users.

This PR offers an optional configuration to fetch custom claims with the profile and updates the docs to describe how to do it.

### Check List
If not relevant to pull request, check off as complete

- [ x ] All tests passing
- [ x ] Docs updated with any changes or examples if applicable
- [ x ] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by 0x80** [comment]
@joerex 	It looks like you forgot to (re)base your commits on the next branch. There are loads of commits included that aren't yours and 163 changed files in total.

**Comment by prescottprue** [comment]
@joerex your changes look great, nice work! If we point it to `master` or rebase/start from `next`, then we can get it merged in

**Comment by prescottprue** [comment]
Used `cherry-pick` for [this commit](https://github.com/prescottprue/react-redux-firebase/pull/741/commits/7f8f693969570c46fa57faa224acadb47e9d949a) by @joerex to get this into [v3.0.0-alpha.15](https://github.com/prescottprue/react-redux-firebase/pull/744).

**Comment by prescottprue** [comment]
Also added to a PR for v2.4.0 so it can go into latest. Thanks again @joerex

**Pull request closed without merging**
