### PR TITLE
[v2.0.0] feat(reducers): authError reducer to mirror authError state in v1

### PR DESCRIPTION
**Pull request by marekolszewski**
### Description
V2 appears to have dropped the firebase.authError redux state present in v1.x. This PR adds it back to maintain better backwards compatibility.

### Check List
If not relevant to pull request, check off as complete

- [X] All tests passing
- [X] Docs updated with any changes or examples if applicable
- [X] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by prescottprue** [comment]
@marekolszewski Nice work! Thanks for following the JSDoc comment pattern, that makes keeping docs updated much easier.

Originally leaving `authError` out was intentional so that everything would be handled with the errors reducer, but it makes more sense to keep it more compatible with v2.

**Comment by nehvaleem** [comment]
@prescottprue - could you please tell me when you plan to publish beta.6 to npm? I could use this authError in my project :)

**Comment by prescottprue** [comment]
@nehvaleem Apologies, I was hosting an event over the last view days.

It should be able to be published tonight after I confirm a few things.

**Comment by prescottprue** [comment]
@nehvaleem It has been released with a few docs updates. 

Future releases should not be held up, I'm working with a few people to help lighten the load.

**Comment by nehvaleem** [comment]
@prescottprue awesome! thanks for your support.

**Pull request merged**
