### PR TITLE
Upgrade typescript definitions

### PR DESCRIPTION
**Pull request by rscotten**
### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
- [x] Docs updated with any changes or examples if applicable
- [x] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by Artem-Ostankov** [comment]
👍 nice

**Comment by Artem-Ostankov** [comment]
thanks a lot for adding all the types 🙏

**Comment by rscotten** [comment]
@Artem-Ostankov you're welcome! 😄

**Comment by Artem-Ostankov** [comment]
@rscotten, could you please share the example project with typescript if you have one.
like https://github.com/prescottprue/react-redux-firebase/tree/next/examples/complete/simple
but with typescript ? Would be great for newcomers to use at as reference if it would be in `examples` ...

**Comment by prescottprue** [comment]
@Artem-Ostankov I just pushed a simple typescript example to the `next` branch. It was created by using `create-react-app <project name> --typescript`, so it didn't start with any types, but I did put react-redux-firebase in there (mirroring the simple example).

**Pull request merged**
