### PR TITLE
more TypeScript definition updates

### PR DESCRIPTION
**Pull request by rscotten**
### Check List
If not relevant to pull request, check off as complete

- [ ] All tests passing
- [ ] Docs updated with any changes or examples if applicable
- [ ] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by rscotten** [comment]
@idanlo I tried my best to merge in your changes here, but it was a bit difficult to line everything up due to working off of different versions.  

Anyway, could you please take a gander and let me know if I've missed anything?

**Comment by prescottprue** [comment]
@rscotten No real value there, feel free to remove it. I was just trying things while working on the typings one time 😆

**Comment by rscotten** [comment]
@idanlo thanks.  updated

**Comment by rscotten** [comment]
@prescottprue haha, removed it.  Thanks

**Comment by rscotten** [comment]
@prescottprue I'm just going to commit to this PR when I see changes that need to be made.  

Perhaps you can merge this right before you're ready to release the next version.  That way I can easily continue to make updates up until the next release.

**Pull request merged**
