### PR TITLE
feat(typings): major improvement to typescript definitions (including types from @firebase)

### PR DESCRIPTION
**Pull request by rscotten**
### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
(n/a) Docs updated with any changes or examples if applicable
(n/a) Added tests to ensure new feature(s) work properly

### Relevant Issues
Types are incomplete but an improvement

### CODE REVIEW

**Comment by prescottprue** [comment]
So much detail in here, thanks

**Comment by idanlo** [comment]
@rscotten I will clean this up later because some types are not needed and provided by firebase, for example `firebase.UserInfo`

**Comment by rscotten** [comment]
@idanlo yeah, I'm merging in your changes right now.  Lots of good stuff in your version.  I'll have another PR ready by end of day

**Comment by prescottprue** [comment]
I went ahead and released v3.0.0-alpha.7 with those changes (since there were other features going out anyway). Any updates either of you make in new PR(s) I'll make sure to try to get released quickly. Thanks again

**Pull request merged**
