### PR TITLE
feat(auth): enable claims without userProfile

### PR DESCRIPTION
**Pull request by rscotten**
### Description

This PR allows allows the developer to `enableClaims` without having a `userProfile`, e.g.:

```typescript
const rrfConfig: Partial<ReactReduxFirebaseConfig> &
  Partial<ReduxFirestoreConfig> = {
  enableClaims: true,
  // userProfile: 'users',
  // useFirestoreForProfile: true,
  logListenerError: process.env.NODE_ENV !== 'production',
};
```

For instance, I was previously using Firestore for my `users` collection, and that collection was at the root level.  

I had to relocate the `users` collection to be a subcollection of `customers` creating the path `customers/{customerId}/users`.

I don't know the `customerId` at the time of bootstrapping my app, so I can't do something like:

```typescript
const rrfConfig: Partial<ReactReduxFirebaseConfig> &
  Partial<ReduxFirestoreConfig> = {
  userProfile: `customers/${customerId}/users`, // Not possible
  useFirestoreForProfile: true,
  logListenerError: process.env.NODE_ENV !== 'production',
};
```

But I can store the `customerId` in the Firebase Auth custom claims, and use that to determine the customer account the user can access.  Hence this PR.

### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
- [x] Docs updated with any changes or examples if applicable
- [x] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by rscotten** [comment]
@prescottprue Good to go.  Please merge.

**Comment by rscotten** [comment]
@prescottprue Good to go. Please merge.

**Comment by rscotten** [comment]
@prescottprue Hey Scott, anything I can do to help this get merged?

**Comment by rscotten** [comment]
@prescottprue hey Scott, it's been 25 days since I checked this in.  Can you please respond?

**Comment by rscotten** [comment]
@prescottprue Can you please respond?

**Comment by prescottprue** [comment]
Hey - thanks for making the PR. Will look into it now

**Pull request merged**
