### PR TITLE
v2.5.1 remove lifecycle warning of using componentWillMount

### PR DESCRIPTION
**Pull request by lidaof**
### Description
sorry I am not a git pro....I created a branch based on 2.5.0 and then made edits based on that commit.

### Check List
If not relevant to pull request, check off as complete

- [ ] All tests passing
- [ ] Docs updated with any changes or examples if applicable
- [ ] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by wurst-case** [comment]
Where are we on this? How can I help resolve this?

**Comment by prescottprue** [comment]
@wurst-case Thanks for the reminder - it was just waiting on me to make a branch which is pointing to the latest v2 commit (v2.5.0). Also going to setup publishing for the v2 series to a tag so that the latest v2 can always be available

**Comment by prescottprue** [comment]
v2.5.1 has been released with the changes - now the `previous` branch and npm tag contain the current v2 version (couldn't use v2 as npm doesn't allow semver version in tags).

Will add a note to the README about this

**Comment by lidaof** [comment]
Hi @prescottprue @wurst-case the edits I made just removed the warnings. Have you guys consider replace `componentWillMount` with `getDerivedStateFromProps` or `componentDidUpdate`? I think this will make it work with React 17 in future. or people should switch to v3...

**Pull request merged**
