### PR TITLE
v2.0.0-beta.11

### PR DESCRIPTION
**Pull request by prescottprue**
### Description
* fix(populate): missing childKey causes no population - #277 (thanks @JeremyPlease)
* feat(firestore): `firestoreConnect` - React HOC that sets listeners to Cloud Firestore (similar to `firebaseConnect`, but for Cloud Firestore instead of Real Time Database) - #286
* feat(firestore): `firestoreReducer` is exported from [`redux-firestore`](https://github.com/prescottprue/redux-firestore) included to handle managing `firestore` state - #286
* feat(core): `withFirebase` - React HOC for just passing `props.firebase` (`firebaseConnect` without any listener management)
* feat(docs): Firestore page added to docs (outlining usage of `firestoreConnect` and `setListener`)
* feat(examples): Firestore complete example added
* feat(docs): README and Query examples simplified + improved
* feat(docs): FAQ moved to its own docs page

**NOTE**: After the Firestore API (including `firestoreConnect`) is stabilized, the `v2.0.0` pre-releases should be ready for release candidate status (pending other major bugs).

### Check List
If not relevant to pull request, check off as complete

- [X] All tests passing
- [X] Docs updated with any changes or examples if applicable
- [ ] Added tests to ensure new feature(s) work properly

### Relevant Issues
 * #277
* #286

### CODE REVIEW

**Comment by JeremyPlease** [comment]
@prescottprue I'm having some issues installing from a git url, so it would be awesome if this pre-release could be released. Is there anything I can do to help?

**Comment by prescottprue** [comment]
@JeremyPlease Yeah you will not be able to install from the git url since the built code is not actually stored on git (it gets published to npm though).

The one thing that has been holding it up is getting the initial phases of Firestore stuff in here too. It should be able to be released tonight.

**Comment by JeremyPlease** [comment]
Thanks @prescottprue! I'll look out for a pre-release later.

I'll be mindful of v2 docs and any issues I come across and report/contribute where I can.

Just FYI:  
I was actually installing with `npm i https://github.com/prescottprue/react-redux-firebase/tarball/v2.0.0-beta.11` and using the npm `postinstall` hook to trigger the `prepublish` script. This ran into some babel/webpack issues though. For the future, we should switch from `prepublish` to `prepare` so that code is build on git install (https://github.com/npm/npm/issues/3055#issuecomment-304698029)

**Comment by prescottprue** [comment]
@JeremyPlease Was planning on moving to prepare anyway, but totally didn't know that it did installs on git install, great to know.

**Review by Amnat-auyana1998 — APPROVED** [review]
👍👍
@prescottprue

**Review by Amnat-auyana1998 — COMMENTED** [review]
👀@prescottprue

**Pull request merged**
